# PHP with fpm serve
FROM php:8.2-fpm

# install php libs and updates
RUN apt-get update && apt-get install -y \
		libfreetype-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
    # DEPENDENCIAS DO PHP
    && docker-php-ext-install gd pdo pdo_pgsql \
	&& docker-php-ext-install -j$(nproc) gd

WORKDIR /var/www

USER www-data

EXPOSE 9000