version: '3.8'

services:
  laravel: # container laravel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./picpay:/var/www
    environment: # configuração de chaves de ambiente
      - APP_ENV=local
      - APP_KEY=base64:your-app-key-here # desnecessário, configurar com php artisan key:generate
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=picpay
      - DB_USERNAME=your-username # configurar postgre user
      - DB_PASSWORD=your-password # configurar postgre pass

  nginx: # container nginx
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # nginx conf file path
      - ./picpay:/var/www
    ports:
      - "80:80" # porta do servidor 
    depends_on:
      - laravel # dependencia, container laravel

  postgres: # container postgres
    image: postgres:15
    environment: 
      POSTGRES_USER: your-username # configurar postgre user
      POSTGRES_PASSWORD: your-password # configurar postgre pass
      POSTGRES_DB: picpay
    volumes:
      - pgdata:/var/lib/postgresql/data # conf path postgres
    ports:
      - "5432:5432"

volumes:
  pgdata:
