# use php apache image
FROM php:8.2.2-apache

# install php extensions and dependencies
RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    libcurl4-openssl-dev \
    libpng-dev \
    libjpeg-dev \
    libpq-dev \
    libonig-dev \
    && docker-php-ext-install gd curl mbstring pdo pdo_pgsql zip

# install composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# install node js and yarn? | não necessário
 
# set work dir
WORKDIR /var/www/html

# expose application ports
EXPOSE 8000

# start apache
CMD ["apache2-foreground"]
