version: '3.8'

services:
  php-app: # container
    build: .
    container_name: php-container # nome do container no docker-hub? | nome do arquivo dockerFile?
    ports:
      - "5432:5432" # postgres    
    volumes:
      - ../picpay:/var/www/html
    depends_on:
      - postgres-db
    environment: # configuração de chaves de ambiente
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: picpay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

  postgres-db: # container postgres
    image: postgres
    container_name: postgres-container
    ports:
      - "5431:5432"
    networks:
      - my-network
    environment: 
      POSTGRES_DB: picpay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

networks:
  my-network: